/**
 * roBrowser overrides for Ragnarok Offline.
 *
 * api.html merges ROConfigBase (Config.js) with this, so it is the supported
 * way to configure the client without patching the build. Loaded directly as
 * a page rather than through an iframe: TYPE.FRAME nests the game in a second
 * browsing context, which swallows keyboard focus (no chat input, no movement
 * keys) for no benefit when the game already owns the whole window.
 */
window.ROConfigLocal = {
	// Client bundle, GRF assets and the game socket all come from our asset
	// server on :3338, so everything is same-origin.
	remoteClient: '/',
	servers: [
		{
			display: 'Ragnarok Offline',
			desc: 'local rAthena',
			// This is a TCP destination for the host-side WebSocket proxy,
			// not the browser's own loopback. A public web hostname must never
			// become a :6900 dial target. The proxy has an exact local allowlist.
			address: '127.0.0.1',
			port: 6900,
			version: 55,
			// The codepage every table the client ships is read with, and
			// `write_client_config` rewrites it to follow Settings -> Game text.
			//
			// 0 is windows-949, which is what the English translation wants:
			// it is ASCII-compatible, so the overlay is untouched and whatever
			// Korean it does not cover renders as actual Korean rather than
			// mojibake ("¼¼»òÀ»"). With the overlay off and a Latin American
			// or international client it becomes 12, which is windows-1252 --
			// the other way round, a Spanish or Portuguese table read as
			// windows-949 pairs its accented bytes up and comes out as Hangul.
			langtype: 0,
			packetver: 20221005,
			renewal: true,
			worldMapSettings: { episode: 20 },
			packetKeys: false,
			// location.host, so the port comes along: the proxy is the same
			// origin that served the page.
			socketProxy: (location.protocol === 'https:' ? 'wss://' : 'ws://') + location.host + '/ws/',
			remoteClient: '/',
			adminList: [2000000]
		}
	],
	skipServerList: true,
	skipIntro: true,
	// Without this roBrowser never reads the item, robe, accessory and NPC
	// name tables at all.
	loadLua: true,
	// The refine window. rAthena ships `feature.refineui: on`, so every refiner
	// in the game -- Hollgrehenn in Prontera and the rest -- takes the branch
	// that closes its dialogue and opens the UI instead of the old menu.
	//
	// roBrowser implements that UI and hooks the packet, but every entry point
	// is guarded by `Configs.get("enableRefineUI")`, and unlike the eight other
	// `enable*` flags this one is **not defined in Config.js**. So it reads
	// `undefined` for everybody: the server sends 0x0aa0, the client decides
	// the feature is off, and the player is left facing a blacksmith who has
	// just said "what would you like to refine?" and offers nothing. The
	// client's own warning says to set this -- into a console nobody opens.
	//
	// It has to be `true` here rather than fixed upstream in Config.js because
	// that file is vendored and regenerated by the client build.
	enableRefineUI: true,
	// Let the client's own warnings out.
	//
	// roBrowser replaces `console` with a dummy unless this or `development`
	// is set, so every warning it writes is discarded -- including
	// "Please enable refine UI in your configs", which named the bug above and
	// which nobody could ever have seen. It is also why state/client.log and
	// the diagnostics report players attach to issues came back empty: the app
	// captures the game page's console faithfully, and there was nothing in it.
	//
	// Costs nothing visible -- players do not have devtools open -- and turns
	// the log into something worth asking a bug reporter for.
	enableConsole: true,
	// Windows follow the 2026 official client. Each switch below keeps a
	// roBrowser extra in the fork; the app turns them off:
	// Status attached under Equipment, the world map's toggle-all-maps button
	// and preview tooltip, the chat "battle mode" strip, and the mercenary
	// gauges in place of the official end date and counters.
	equipmentStatusEmbedded: false,
	worldMapExtras: false,
	chatBattleModeBar: false,
	mercenaryGauges: false,
	// The official renewal hotbar (-/+ rows, Skill Bar 1/2), roBrowserLegacy#15.
	// Off by default in roBrowser, where the classic hotbar shows.
	enableRenewalShortCut: true,
	// The official layouts of rebuilt windows (Vending, Navigation, Roulette),
	// roBrowserLegacy#16, #18 and #19. Unset in roBrowser, where its own windows show.
	officialLayout: true,
	BGMFileExtension: ['mp3']
};
